= Jira Release Notes Generator (JiraRnGen)
:Author: David Thompson 
:Email: <dthompsn1@gmail.com>
:Revision: 0.1.0 2016-08-03

== Description
I was looking for a way with hosted Jira to be able to send out release
notes with our own template. Since the hosted version doesn't allow you to
edit the templates, I decided to build an application that worked with the
Jira api to build an html page that could be emailed to our team. This NodeJS
app is the result of this work.

== ReleaseNotes
0.1.0 - First iteration at being able to send Jira Release Notes

== Usage
First time to use, run within the JiraRnGen directory.
----
$ npm install
----
You will need to create a image/logo.json file; you can copy the example to logo.json for testing.
You will need to set up a sendgrid account and set up an API key to use with sendgrid. Copy conf/config-example.json to conf/config.json.

Then to run each time
----
$ node release-notes.js -u username -p password --email -n jira-hostname -f release-name -s email-address
----
